#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin2.Android.Resource", IsApplication=true)]

namespace Xamarin2.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AmanWalia = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AnilSethi = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BhavnaPruthi = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int GagandeepSingh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int HarpreetKaur = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_content_new = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int KetanSharma = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ManishSingh = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int MeenalSharma = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int MohdRiyaz = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int NainaSharma = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int NazarNaqvi = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int NehaGupta = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int PardeepTandon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int RupreetGujral = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ShagunBawa = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Techizzaa = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int GridButton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int ListButton = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int PersonGridview = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int SimpleButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int imgView = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int techizzianListView = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int txtViewName = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int txtViewTitle = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GridAdapter = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GridAdapterLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PersonGrid = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TechizzianLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TechizzianListPage = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
